import React from "react";
import style from './style.module.scss';
export const Spinner = () =>{

    return (
        <div className={style['container__spinner']}>
            <div class='spinner'>
            <i>
            <b></b>
            </i>
            <i>
            <b></b>
            </i>
            <i>
            <b></b>
            </i>
            <i>
            <b></b>
            </i>
            <i>
            <b></b>
            </i>
            <i>
            <b></b>
            </i>
            <i>
            <b></b>
            </i>
            <i>
            <b></b>
            </i>
            <i>
            <b></b>
            </i>
            <i>
            <b></b>
            </i>
            <i>
            <b></b>
            </i>
            <i>
            <b></b>
            </i>
            <i>
            <b></b>
            </i>
            <i>
            <b></b>
            </i>
            <i>
            <b></b>
            </i>
            <i>
            <b></b>
            </i>
            <i>
            <b></b>
            </i>
            <i>
            <b></b>
            </i>
            <i>
            <b></b>
            </i>
            <i>
            <b></b>
            </i>
            <i>
            <b></b>
            </i>
            <i>
            <b></b>
            </i>
            <i>
            <b></b>
            </i>
            <i>
            <b></b>
            </i>
            <i>
            <b></b>
            </i>
            <i>
            <b></b>
            </i>
            <i>
            <b></b>
            </i>
            <i>
            <b></b>
            </i>
            <i>
            <b></b>
            </i>
            <i>
            <b></b>
            </i>
            <i>
            <b></b>
            </i>
            <i>
            <b></b>
            </i>
            <i>
            <b></b>
            </i>
            <i>
            <b></b>
            </i>
            <i>
            <b></b>
            </i>
            <i>
            <b></b>
            </i>
            <i>
            <b></b>
            </i>
            <i>
            <b></b>
            </i>
            <i>
            <b></b>
            </i>
            <i>
            <b></b>
            </i>
            <i>
            <b></b>
            </i>
            <i>
            <b></b>
            </i>
            <i>
            <b></b>
            </i>
            <i>
            <b></b>
            </i>
            <i>
            <b></b>
            </i>
            <i>
            <b></b>
            </i>
            <i>
            <b></b>
            </i>
            <i>
            <b></b>
            </i>
            <i>
            <b></b>
            </i>
            <i>
            <b></b>
            </i>
            <i>
            <b></b>
            </i>
            <i>
            <b></b>
            </i>
            <i>
            <b></b>
            </i>
            <i>
            <b></b>
            </i>
            <i>
            <b></b>
            </i>
            <i>
            <b></b>
            </i>
            <i>
            <b></b>
            </i>
            <i>
            <b></b>
            </i>
            <i>
            <b></b>
            </i>
            <i>
            <b></b>
            </i>
            <i>
            <b></b>
            </i>
            <i>
            <b></b>
            </i>
            <i>
            <b></b>
            </i>
            <i>
            <b></b>
            </i>
            <i>
            <b></b>
            </i>
            <i>
            <b></b>
            </i>
            <i>
            <b></b>
            </i>
            <i>
            <b></b>
            </i>
            <i>
            <b></b>
            </i>
            <i>
            <b></b>
            </i>
            <i>
            <b></b>
            </i>
            <i>
            <b></b>
            </i>
            <i>
            <b></b>
            </i>
            <i>
            <b></b>
            </i>
            <i>
            <b></b>
            </i>
            <i>
            <b></b>
            </i>
            <i>
            <b></b>
            </i>
            <i>
            <b></b>
            </i>
            <i>
            <b></b>
            </i>
            <i>
            <b></b>
            </i>
            <i>
            <b></b>
            </i>
            <i>
            <b></b>
            </i>
            <i>
            <b></b>
            </i>
            <i>
            <b></b>
            </i>
            <i>
            <b></b>
            </i>
            <i>
            <b></b>
            </i>
            <i>
            <b></b>
            </i>
            <i>
            <b></b>
            </i>
            <i>
            <b></b>
            </i>
            <i>
            <b></b>
            </i>
            <i>
            <b></b>
            </i>
            <i>
            <b></b>
            </i>
            <i>
            <b></b>
            </i>
            <i>
            <b></b>
            </i>
            <i>
            <b></b>
            </i>
            <i>
            <b></b>
            </i>
            <i>
            <b></b>
            </i>
            <i>
            <b></b>
            </i>
            <i>
            <b></b>
            </i>
            <i>
            <b></b>
            </i>
            </div>
        </div>
    )
}